### ISSUE TITLE
Métricas de desempenho

### ISSUE THREAD

**Issue by EduardoMCF** [FMota0/kimpl#9]
O projeto é bem bacana e eu seria facilmente um usuário desse sistema. Enquanto usuário eu iria gostar muito de ter algumas métricas e plots relacionados ao meu progresso em cada área. Um plot bem simples e interessante, por exemplo, envolveria quantidade de problemas resolvidos e o nível de dificuldade, isso para cada categoria.

**Comment by FMota0** [comment]
A intenção do projeto não é ir nessa direção, mas ficar como algo mais simples
